services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_hunter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql


  analytics-api:
    build: ./analytics
    container_name: analytucs-api
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT": 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: digital_hunter
    ports:
      - "8000:8000"
    networks:
      - backend


volumes:
  mysql_data:
